// Network Information
export const FETCH_BLOCK_HEIGHT_ERROR = 'FETCH_BLOCK_HEIGHT_ERROR';
export const FETCH_BLOCK_HEIGHT_REQUEST = 'FETCH_BLOCK_HEIGHT_REQUEST';
export const FETCH_BLOCK_HEIGHT_SUCCESS = 'FETCH_BLOCK_HEIGHT_SUCCESS';

export const FETCH_NETWORK_HASH_ERROR = 'FETCH_NETWORK_HASH_ERROR';
export const FETCH_NETWORK_HASH_REQUEST = 'FETCH_NETWORK_HASH_REQUEST';
export const FETCH_NETWORK_HASH_SUCCESS = 'FETCH_NETWORK_HASH_SUCCESS';

export const FETCH_MARKET_CAP_ERROR = 'FETCH_MARKET_CAP_ERROR';
export const FETCH_MARKET_CAP_REQUEST = 'FETCH_MARKET_CAP_REQUEST';
export const FETCH_MARKET_CAP_SUCCESS = 'FETCH_MARKET_CAP_SUCCESS';

// Wallet
export const FETCH_WALLET_BALANCE_ERROR = 'FETCH_WALLET_BALANCE_ERROR';
export const FETCH_WALLET_BALANCE_REQUEST = 'FETCH_WALLET_BALANCE_REQUEST';
export const FETCH_WALLET_BALANCE_SUCCESS = 'FETCH_WALLET_BALANCE_SUCCESS';
